version: '3.3'
services:
  web:
    container_name: nutrilife-web
    build: .
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres-db
      DB_USER: kelompokD
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: nutrilife
      DB_PORT: 5432
    volumes:
      - "./:/app"

  postgres:
    image: postgres:latest
    container_name: postgres-db
    env_file:
      - .env
    restart: always
    ports:
      - 5434:5432
    environment:
      POSTGRES_ROOT_PASSWORD: kelompokD
      POSTGRES_DB: nutrilife
      POSTGRES_USER: kelompokD
      POSTGRES_PASSWORD: ${DB_PASSWORD}
